### ISSUE TITLE
Typos in Readme

### ISSUE THREAD

**Issue by AlexanderJCS** [QEDjl-project/QEDbase.jl#12]
When reading the `README.md` file, I noticed that there was a small typo in the word "contributor". It is spelled "contributer". It is spelt incorrectly two times:

```
## Credits and contributers
```

and:
```
- the guy who will show me how to include the most recent contributers on github
```

This seems parallel to issue #10 which proposes to update the contributors section entirely.

**Comment by szabo137** [comment]
Thanks for reaching out! I copied this to the respective `update readme` issue. Therefore, this will be closed in favor of #10
