### ISSUE TITLE
repair local doc build

### ISSUE THREAD

**Issue by SimeonEhrig** [QEDjl-project/QEDbase.jl#21]
At the moment, it is not possible to build the documentation locally because of several bugs.

**Comment by szabo137** [comment]
Could you please provide a screenshot of the error message? I guess it is a newer version of `DocumenterCitations.jl`, which removes the keyword `sorting` from their `CitationBibliography`.

**Comment by SimeonEhrig** [comment]
The `CitationBibliography` packages is the problem. The removed `sorting` argument is one problem. The other is passing the `bib` struct to `makedocs`. Looks like they changed the [interface](https://documenter.juliadocs.org/stable/lib/public/#Documenter.makedocs):

```julia
$ julia --project=docs/ docs/make.jl 
ERROR: LoadError: MethodError: no method matching makedocs(::CitationBibliography; modules::Vector{Module}, checkdocs::Symbol, authors::String, repo::String, sitename::String, format::Documenter.HTMLWriter.HTML, pages::Vector{Any})

Closest candidates are:
  makedocs(; debug, format, kwargs...)
   @ Documenter ~/.julia/packages/Documenter/Meee1/src/makedocs.jl:241

Stacktrace:
 [1] top-level scope
   @ ~/projects/QED-project/QEDbase.jl/docs/make.jl:24
in expression starting at /home/user/projects/QED-project/QEDbase.jl/docs/make.jl:24

```
