### ISSUE TITLE
Update outdated docstrings!

### ISSUE THREAD

**Issue by szabo137** [QEDjl-project/QEDbase.jl#33]
Isn't `base_state()` part of QEDbase with this PR?

_Originally posted by @steindev in https://github.com/QEDjl-project/QEDbase.jl/pull/25#discussion_r1354544020_
            
              This import is probably not required anymore?

_Originally posted by @steindev in https://github.com/QEDjl-project/QEDbase.jl/pull/25#discussion_r1354545945_

**Comment by steindev** [comment]
@szabo137 this can be closed now, can't it?
