### ISSUE TITLE
cross_section and probability interface exports

### ISSUE THREAD

**Issue by AntonReinhard** [QEDjl-project/QEDbase.jl#86]
Currently, QEDbase.jl exports the functions
- `unsafe_differential_cross_section`
- `differential_cross_section`
- `total_cross_section`
- `unsafe_differential_probability`
- `differential_probability`
- `total_probability`

However, it does not define them in any way. This is definitely an issue because they cannot be overridden (because they are undefined) but re-exporting them in a different package still creates a collision requiring a namespace qualifier to use them. The question is where to keep the implementations in the future. Right now they are in QEDprocesses.jl. The functions seem basic enough to be part of either QEDbase or QEDcore, and since they are in a way convenience functions based on top of an interface, I suggest moving them to QEDcore.

**Comment by szabo137** [comment]
Oh, this should be added here because defining them anywhere else, would end up being type piracy in one way or another. 

I will open a PR later today.

**Comment by AntonReinhard** [comment]
Solved with #87
